server:
  port: 8021

spring:
  application:
    name: index-data-server  #指数代码的数据服务
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
  redis:
    port: 6379
    host: localhost

# 激活Sentinel对Feign的支持
#feign:
#  sentinel:
#    enabled: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*' #暴露监控地址